### ISSUE TITLE
Kann es sein, dass hier drin 1:1 Kopien aus dem WLANThermo drin sind?

### ISSUE THREAD

**Issue by arminth** [sbiermann/rpi-grillthermo#1]
Hallo sbiermann,
das Entwicklerteam des wlanthermo ist über dein GIT-repository gestolpert.
Irgendwie kommt uns da einiges sehr bekannt vor. Der Urheber der Dateien wird nirgends erwähnt.
Ich verweise auf das Original-Repository https://github.com/WLANThermo. Dieses unterliegt der GPL!
Sollte es sich um einen Test gehandelt haben (seit Juli 2015 ist nichts gelaufen hier) wäre es wohl sinnvoll, dies hier zu beenden.
Wenn Du bei der Weiterentwicklung des wlanthermos mitarbeiten möchtest, bist du jederzeit dazu eingeladen.
Mit freundlichen Grüßen

arminth

**Comment by sbiermann** [comment]
Hallo Armin,
danke für deinen Hinweis, ich habe die Lizenz umgeändert auf GPLv3 so wie Ihr es auch habt. Damals als ich den Sourcecode extrahiert habe gab es noch kein Git Repository von Euch, daher wusste ich nicht welche Lizenz Ihr gewählt habt. Es stand leider nicht in den Dateien drin die ich aus dem Install script extrahiert hatte. Daher habe ich einfach die Apache Lizenz gewählt. Ich habe jetzt in der Readme.md rein geschrieben das es in einigen Funktionen auf Eurem Code basiert und habe Eure Sourcen wlt2_*.py gelöscht. Letzteres brauche ich ja nun nicht mehr da Ihr ja auch ein Repository bei Github habt und ich dort schauen kann wie ihr das umgesetzt habt. Das war auch der einzige Grund warum es dieses Verzeichnis mit den Dateien gab.
Vielen Dank für deine Einladung zur Mitarbeit am WLANThermo, ich fürchte allerdings das meine Idee von der Umsetzung einen WLAN Thermometers mittlerweile zu stark von Eurer abweicht. So dass ich vermutlich nichts zu Eurer Version beisteuern kann. Aber falls Ihr in Eurer Version 3 des WLANThermo MQTT einsetzen wollt und dazu noch dedizierte Temperatursensoren per ESP8266 können wir uns gerne austauschen. Denn dies ist die neuste Idee wie ich das Projekt umsetzen werde. Ich warte nur noch auf die Teile aus China.

Nochmals vielen Dank für deinen Hinweis! Wenn dies soweit ok für Euch ist, würde ich dieses Ticket dann schließen wollen.

Viele Grüße
Stefan

**Comment by arminth** [comment]
Alles klar. Passt. Kann zu.
